### ISSUE TITLE
jinja2和flask版本冲突问题

### ISSUE THREAD

**Issue by dfmjndm** [bailuWX/MajsoulAI-fix#6]
File "D:\ANACONDA\envs\majsoul\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (D:\ANACONDA\envs\majsoul\lib\site-packages\markupsafe\__init__.py)

有人说要把jinja2升到3.0.3才能解决，这样会与flask 1.1.4冲突，然后导致mitmproxy6.0.2不能用。我试了7.0的版本，7.0修改了一些函数的位置
mitmproxy 6.0.2 requires flask<1.2,>=1.1.1, but you have flask 2.0.3 which is incompatible.

**Comment by dfmjndm** [comment]
需要1.1.1的markupsafe

**Comment by bailuWX** [comment]
我之前改bug遇到了很多报错，但是暂时还没遇到你的这些error。。我遇到的大部分都在原作者的issues里面出现了，上面会有很多解决方案。
另，我更新了一下readme的注意事项。可以看看

**Comment by bailuWX** [comment]
另外，mitm的版本最好是mitmproxy6.0.2左右的，实测7 会和一些包产生冲突、。。
