### ISSUE TITLE
你好大佬请教一下

### ISSUE THREAD

**Issue by hanfu3** [bailuWX/MajsoulAI-fix#9]
有没一种可能把雀魂对局转换成mjai格式输出

**Comment by Pragmatism0220** [comment]
我最近也在试着实现这个，mjai格式的标准还是比较好写的。不过你是怎么处理收到的websocket数据的呢？这个仓库也比较老了，我刚试了一下，liqi也解析不了，怀疑是解析算法更新了

**Comment by hanfu3** [comment]
留个联系方式交流一下

**Comment by hanfu3** [comment]
> > 有没一种可能把雀魂对局转换成mjai格式输出
> 
> 我最近也在试着实现这个，mjai格式的标准还是比较好写的。不过你是怎么处理收到的websocket数据的呢？这个仓库也比较老了，我刚试了一下，liqi也解析不了，怀疑是解析算法更新了

是的就这一部分比较难

**Comment by Pragmatism0220** [comment]
> > > 有没一种可能把雀魂对局转换成mjai格式输出
> > 
> > 
> > 我最近也在试着实现这个，mjai格式的标准还是比较好写的。不过你是怎么处理收到的websocket数据的呢？这个仓库也比较老了，我刚试了一下，liqi也解析不了，怀疑是解析算法更新了
> 
> 是的就这一部分比较难

在接收牌局信息的时候会报错，但是解析昵称点数等就没有问题，很奇怪。你有什么思路或者实现吗？

**Comment by hanfu3** [comment]
> > > > 没有一种可能把雀魂对局转换成mjai格式输出
> > > 
> > > 
> > > m着这个这个这个这个，mjai格式格式的还还是好的也也也写写的的的。不过是是的的的的的的的的的的的的数据数据数据数据数据数据的呢呢呢个个库也也也也也也也也也也也
> > 
> > 
> > 是的就这一部分比较难
> 
> 在接收品牌局信息的时候会报错，但是解析泛指点数等就没有问题，很奇怪。你有什么想法或者现实吗？

应该是一部分的protobuf格式被改了。 加了混淆。解析相关函数比较困难。 
有别人能用的源码不知道是否可以参考

**Comment by Pragmatism0220** [comment]
> > > > > 没有一种可能把雀魂对局转换成mjai格式输出
> > > > 
> > > > 
> > > > m着这个这个这个这个，mjai格式格式的还还是好的也也也写写的的的。不过是是的的的的的的的的的的的的数据数据数据数据数据数据的呢呢呢个个库也也也也也也也也也也也
> > > 
> > > 
> > > 是的就这一部分比较难
> > 
> > 
> > 在接收品牌局信息的时候会报错，但是解析泛指点数等就没有问题，很奇怪。你有什么想法或者现实吗？
> 
> 应该是一部分的protobuf格式被改了。 加了混淆。解析相关函数比较困难。 有别人能用的源码不知道是否可以参考

你可以提交一个仓库或者gist吗，如果是可以使用的话，我想参考一下。是什么语言的呢？

**Comment by Pragmatism0220** [comment]
> > > > > > > 没有一种可能把雀魂对局转换成mjai格式输出
> > > > > > 
> > > > > > 
> > > > > > m着这个这个这个这个，mjai格式格式的还还是好的也也也写写的的的。不过是是的的的的的的的的的的的的数据数据数据数据数据数据的呢呢呢个个库也也也也也也也也也也也
> > > > > 
> > > > > 
> > > > > 是的就这一部分比较难
> > > > 
> > > > 
> > > > 在接收品牌局信息的时候会报错，但是解析泛指点数等就没有问题，很奇怪。你有什么想法或者现实吗？
> > > 
> > > 
> > > 应该是一部分的protobuf格式被改了。 加了混淆。解析相关函数比较困难。 有别人能用的源码不知道是否可以参考
> > 
> > 
> > 你可以提交一个仓库或者gist吗，如果是可以使用的话，我想参考一下。是什么语言的呢？
> 
> 这个不太方便公布，可以加个好友这边发给你看看

加个好友吧，qq可以吗，我的q是1925583549
